# Generated by Django 2.2.1 on 2019-10-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='text',
            field=models.TextField(default='empty'),
        ),
        migrations.AlterField(
            model_name='header',
            name='email_title',
            field=models.CharField(max_length=250),
        ),
    ]
